# Generated by Django 6.0.7 on 2026-07-17 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planetarium_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showsession',
            name='astronomy_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetarium_app.astronomyshow'),
        ),
        migrations.AddField(
            model_name='showsession',
            name='planetarium_dome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetarium_app.planetariumdome'),
        ),
        migrations.AddField(
            model_name='astronomyshowtheme',
            name='show_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetarium_app.showtheme'),
        ),
        migrations.AddField(
            model_name='astronomyshow',
            name='themes',
            field=models.ManyToManyField(through='planetarium_app.AstronomyShowTheme', to='planetarium_app.showtheme'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetarium_app.reservation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='show_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planetarium_app.showsession'),
        ),
        migrations.AlterUniqueTogether(
            name='astronomyshowtheme',
            unique_together={('astronomy_show', 'show_theme')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('show_session', 'row', 'seat')},
        ),
    ]
